spring:
  datasource:
    username: root
    url: jdbc:mysql://database:3306/author
    driverClassName: com.mysql.cj.jdbc.Driver
    password: strongpassword
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    show-sql: 'true'
    hibernate:
      ddl-auto: update
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_HOST:http://eurekaserver:8080/eureka/}
    register-with-eureka: true
    fetch-registry: true
  instance:
    instance-id: author-instance
    preferIpAddress: true
